CREATE DATABASE soron_monika_KCS2025
character SET utf8
COLLATE utf8_hungarian_ci;

USE soron_monika_KCS2025;

CREATE TABLE Product(
SEID VARCHAR (20) PRIMARY KEY,
Manufacturer VARCHAR (50),
MODEL VARCHAR (100) NOT NULL,
DataReceived date DEFAULT CURRENT_DATE
);

CREATE TABLE ContactPerson(
CID VARCHAR (20) PRIMARY KEY,
NAME VARCHAR (20),
PHONE VARCHAR (20) NOT NULL,
EMAIL varchar(100)
);

CREATE TABLE Service(
SID VARCHAR (20) PRIMARY KEY,
SEID VARCHAR (20) NOT NULL,
CID VARCHAR (20) NOT NULL,
Status enum('Beérkezett','Hibafeltárás','Alkatrész beszerzés alatt','Javítás','Kész') DEFAULT('Beérkezett'), 
lastupdate DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
CONSTRAINT FK_ProductSEID_ServiceSEID FOREIGN KEY (SEID) REFERENCES Product(SEID),
CONSTRAINT FK_ContactCID_ServiceCID FOREIGN KEY (CID) REFERENCES ContactPerson(CID)
);
